name: CI/CD – Build, Push, Deploy to EKS


- name: Build & Push Docker image
env:
ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
IMAGE_TAG: ${{ github.sha }}
run: |
docker build -f docker/Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
echo "ECR_REGISTRY=$ECR_REGISTRY" >> $GITHUB_ENV
echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV


- name: Update kubeconfig
run: |
aws eks update-kubeconfig --name "$EKS_CLUSTER_NAME" --region "$AWS_REGION"


- name: Install AWS Load Balancer Controller (idempotent)
run: |
helm repo add eks https://aws.github.io/eks-charts || true
helm repo update
kubectl get ns kube-system || kubectl create ns kube-system
helm upgrade --install aws-load-balancer-controller eks/aws-load-balancer-controller \
-n kube-system \
--set clusterName=$EKS_CLUSTER_NAME \
--set serviceAccount.create=true \
--set region=$AWS_REGION \
--set vpcId=$(aws eks describe-cluster --name $EKS_CLUSTER_NAME --query 'cluster.resourcesVpcConfig.vpcId' --output text) \
--set image.repository=602401143452.dkr.ecr.$AWS_REGION.amazonaws.com/amazon/aws-load-balancer-controller


- name: Create namespace + configmap
run: |
export K8S_NAMESPACE=${K8S_NAMESPACE}
envsubst < k8s/namespace.yaml | kubectl apply -f -
envsubst < docker/nginx.conf > /tmp/nginx.conf
kubectl -n $K8S_NAMESPACE create configmap nginx-config --from-file=nginx.conf=/tmp/nginx.conf --dry-run=client -o yaml | kubectl apply -f -


- name: Deploy app (Deployment + Service + Ingress + HPA)
env:
ECR_REGISTRY: ${{ env.ECR_REGISTRY }}
IMAGE_TAG: ${{ env.IMAGE_TAG }}
run: |
export K8S_NAMESPACE=${K8S_NAMESPACE}
export ECR_REGISTRY=${ECR_REGISTRY}
export ECR_REPOSITORY=${ECR_REPOSITORY}
export IMAGE_TAG=${IMAGE_TAG}
export ACM_CERT_ARN=${ACM_CERT_ARN}
export DOMAIN_NAME=${DOMAIN_NAME}


for f in deployment.yaml service.yaml ingress.yaml hpa.yaml; do \
envsubst < k8s/$f | kubectl apply -n $K8S_NAMESPACE -f -; \
done


- name: Install/Upgrade Monitoring (Prometheus + Grafana)
run: |
bash monitoring/install.sh monitoring


- name: Show ALB hostname
run: |
kubectl get ingress -n ${K8S_NAMESPACE} -o jsonpath='{.items[0].status.loadBalancer.ingress[0].hostname}'